name: Endpoint post

on:
  schedule:
    - cron: "0 14 * * 1,4"
  workflow_dispatch:

jobs:
  post:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "24"

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Run post.js
        run: npm run endpoint:post
        env:
          BLUESKY_IDENTIFIER: "${{ secrets.BLUESKY_IDENTIFIER }}"
          BLUESKY_PASSWORD: "${{ secrets.BLUESKY_PASSWORD }}"
